### ISSUE TITLE
Потенциально опасные команды

### ISSUE THREAD

**Issue by BATCOH** [ant-tr-v/mybot#14]
Некоторые команды для пользователя и для командира выдают разную информацию. В основном это топы.
Случаи, когда новоназначенный командир случайно писал /top squadname в общем чате уже были. А если админ случайно ткнёт по чьей-нибудь команде и бот пойдёт отсылать полный top по фракции? А если админ просто не хочет нигде светить, что он админ?

Предлагаю следующий вариант:
+ Кнопки в личке у бота должны работать как сейчас, выводить полные списки при наличии прав.
+ Команды в чатах выводят урезанные сообщения, как для обычного пользователя.
+ Какое-то дополнение для полного командирского доступа в чате при необходимости, например /sudo top squadname.

**Comment by ant-tr-v** [comment]
Идея не нова
И над ней надо будет поработать

В контексте текущей пададигмы команд можно например. сделать модификатор
_all или _admin или _sudo

Так /top будет показывать топ 5
А /top_all топ по всем с проверкой на админа

**Comment by ant-tr-v** [comment]
реализованно в top - дальше делать по аналогии
